### ISSUE TITLE
not correctly displaying scaleType

### ISSUE THREAD

**Issue by wwwdotphilip** [flavioarfaria/KenBurnsView#40]
When I try to display an image with a scaleType="fitCenter" it doesn't do what it actually does like a normal ImageView.

Here is my code.

    <com.flaviofaria.kenburnsview.KenBurnsView
        android:id="@+id/image"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:src="@drawable/ic_launcher"
        android:scaleType="fitCenter" />

    <Button
        android:id="@+id/button"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:onClick="cyclePhoto"
        android:text="Cycle photo" />

The output show's like this.

<img src="https://cloud.githubusercontent.com/assets/3078483/15804741/d5615d90-2b45-11e6-9cda-149526d1d089.png" alt="screenshot" width="200" height="320">

instead of this

<img src="https://cloud.githubusercontent.com/assets/3078483/15804772/dd9adfee-2b46-11e6-8ff0-b7f611ae200e.png" alt="screenshot" width="200" height="320">

**Comment by flavioarfaria** [comment]
Hi,

This is already expected and works like this by design. KenBurnsView ignores the `imageType` attribute and forces all images to `center_crop` to limit the viewport to the image bounds. That's how the Ken Burns Effect works: https://en.wikipedia.org/wiki/Ken_Burns_effect. If you need your image to be fit-centered, KenBurnsView is not really what you're looking for.
