### ISSUE TITLE
KenBurnsView disable backpress.

### ISSUE THREAD

**Issue by DoubleTime** [flavioarfaria/KenBurnsView#42]
I just realise adding KenBurnsView at my activity will cause the phone physical back button stop working.

Override onBackPressed() no response as well.

**Comment by flavioarfaria** [comment]
Hi DoubleTime,

That seems very unlikely, since KenBurnsView should not affect back navigation. I have a few questions:

1) What's your phone model and OS version?
2) Have you tried on a different phone to see if it happens as well?
3) Could you provide an [MCVE](http://stackoverflow.com/help/mcve)?

**Comment by DoubleTime** [comment]
You are right, I am having trouble with OnePlus One, OS 4.4.2 only.
I tested on other devices, all working well.

**Comment by flavioarfaria** [comment]
Are you getting any error in logcat? Are you having the same problem with a regular `ImageView`?

**Comment by DoubleTime** [comment]
No error in logcat in my device, could be something odd happen to my phone.
Thanks for you response, love your library.
