### ISSUE TITLE
Circle orientation

### ISSUE THREAD

**Issue by tintinscorpion** [flavioarfaria/KenBurnsView#57]
Provide a circle orientation for it else it will get dependent on Image loader libraries for transformation

**Comment by flavioarfaria** [comment]
Hi @tintinscorpion,

This library has solely the purpose of animating images within their boundaries. In order to keep it lightweight and restricted to its own purpose, we'll not bring in functionality that won't benefit the majority of users. In cases like this, I'd suggest developers to import other libraries into their apps.
